# Generated by Django 4.2 on 2026-06-30 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_text", models.TextField()),
                (
                    "mood_tag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Anxious", "Anxious"),
                            ("Hopeful", "Hopeful"),
                            ("Tired", "Tired"),
                            ("Calm", "Calm"),
                            ("Overwhelmed", "Overwhelmed"),
                            ("Grateful", "Grateful"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
