# Generated by Django 4.2 on 2026-07-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="mood_tag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("struggling", "Struggling"),
                    ("overwhelmed", "Overwhelmed"),
                    ("exhausted", "Exhausted"),
                    ("low", "Low"),
                    ("anxious", "Anxious"),
                    ("tired", "Tired"),
                    ("okay", "Okay"),
                    ("neutral", "Neutral"),
                    ("hopeful", "Hopeful"),
                    ("calm", "Calm"),
                    ("grateful", "Grateful"),
                    ("happy", "Happy"),
                    ("energised", "Energised"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
