export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:token',
  HEALTHCARE_CONTACT: '/healthcare-contact',
  MOTHERHOOD_STAGE: '/motherhood-stage',
  PREGNANT_FOLLOW_UP: '/pregnant-follow-up',
  BIRTH_FOLLOW_UP: '/birth-follow-up',
  SEASONED_MOTHER: '/seasoned-mother',
  EXPLORING: '/exploring',
  SAFETY_NET: '/safety-net/:token',
  DASHBOARD: '/dashboard',
  CHECKIN: '/checkin',
  JOURNAL: '/journal',
  CHAT: '/chat',
  EPDS: '/epds',
  EPDS_RESULT: '/epds/result',
  SUPPORT: '/support',
  INSIGHTS: '/insights',
  MOOD_HISTORY: '/mood-history',
  NOTIFICATIONS: '/notifications',
  PROFILE: '/profile',
  PRIVACY: '/privacy',
  ABOUT: '/about',
};
