DAILY_ROUTINES = {
    'pregnant': [
        {
            'title': 'Pelvic floor exercises',
            'description': 'A few gentle squeezes today can make a real difference later — no pressure to be perfect.',
            'duration': '5 minutes',
            'icon': 'stretch',
        },
        {
            'title': 'Drink a glass of water',
            'description': 'Staying hydrated helps your body and your baby, and it is one small thing you can tick off right now.',
            'duration': '2 minutes',
            'icon': 'water',
        },
        {
            'title': 'A short walk outside',
            'description': 'A little fresh air and movement can lift your mood more than you might expect.',
            'duration': '10 minutes',
            'icon': 'walk',
        },
        {
            'title': 'Write one thing you are grateful for',
            'description': 'Noticing even a small good thing can shift how the rest of your day feels.',
            'duration': '2 minutes',
            'icon': 'gratitude',
        },
        {
            'title': 'A breathing exercise',
            'description': 'Slow, deep breaths can calm your body and give you a moment of real stillness.',
            'duration': '5 minutes',
            'icon': 'breath',
        },
        {
            'title': 'Rest without guilt',
            'description': 'Your body is doing something incredible — resting is productive too.',
            'duration': '15 minutes',
            'icon': 'rest',
        },
        {
            'title': 'Call someone you trust',
            'description': 'A quick chat with someone who cares about you can make everything feel a little lighter.',
            'duration': '10 minutes',
            'icon': 'heart',
        },
        {
            'title': 'Gentle stretching',
            'description': 'A few easy stretches can ease tension and help you feel more at home in your body.',
            'duration': '5 minutes',
            'icon': 'stretch',
        },
        {
            'title': 'Review your birth plan with your partner',
            'description': 'Talking through what matters most to you can help you both feel more prepared.',
            'duration': '15 minutes',
            'icon': 'heart',
        },
        {
            'title': 'Read about what to expect during labor',
            'description': 'A little knowledge now can help the unknown feel less daunting later.',
            'duration': '10 minutes',
            'icon': 'read',
        },
        {
            'title': 'Take a moment to write a letter to your baby',
            'description': 'Whatever you want to say, this is a lovely way to mark this time.',
            'duration': '10 minutes',
            'icon': 'journal',
        },
        {
            'title': 'Pack one item for your hospital bag',
            'description': 'One small step today means less to think about later.',
            'duration': '5 minutes',
            'icon': 'bag',
        },
    ],
    'postpartum': [
        {
            'title': 'A 5 minute shower without rushing',
            'description': 'You deserve a few unhurried minutes just for yourself today.',
            'duration': '5 minutes',
            'icon': 'water',
        },
        {
            'title': 'Eat something warm',
            'description': 'Feeding yourself matters too — a warm meal can be surprisingly comforting.',
            'duration': '10 minutes',
            'icon': 'heart',
        },
        {
            'title': 'Step outside for fresh air',
            'description': 'Even a minute of daylight and fresh air can help reset a hard morning.',
            'duration': '2 minutes',
            'icon': 'walk',
        },
        {
            'title': 'Write down one win from today',
            'description': 'No matter how small, it counts — you are doing more than you realise.',
            'duration': '2 minutes',
            'icon': 'journal',
        },
        {
            'title': 'Ask for help with one thing',
            'description': 'You do not have to carry everything alone — letting someone help is a strength, not a failure.',
            'duration': '5 minutes',
            'icon': 'heart',
        },
        {
            'title': 'A short nap if you can',
            'description': 'Sleep is precious right now, and even a short rest can help you recharge.',
            'duration': '20 minutes',
            'icon': 'rest',
        },
        {
            'title': 'Drink a full glass of water',
            'description': 'It is easy to forget yourself while caring for someone else — this one is just for you.',
            'duration': '2 minutes',
            'icon': 'water',
        },
        {
            'title': 'One slow, deep breath',
            'description': 'Just one. Let your shoulders drop and give yourself this small moment of calm.',
            'duration': '1 minute',
            'icon': 'breath',
        },
        {
            'title': 'Learn the difference between baby blues and postpartum depression',
            'description': 'Knowing what is typical and what is worth mentioning to your GP or midwife can bring peace of mind.',
            'duration': '5 minutes',
            'icon': 'read',
        },
        {
            'title': 'Try skin-to-skin contact today',
            'description': 'Even a few quiet minutes of closeness can be soothing for you both.',
            'duration': '10 minutes',
            'icon': 'heart',
        },
        {
            'title': 'Say yes if someone offers to help',
            'description': 'You do not have to do it all today — accepting support is self-care too.',
            'duration': '2 minutes',
            'icon': 'heart',
        },
        {
            'title': 'Notice one moment of joy today',
            'description': 'Even on hard days, small bright moments count.',
            'duration': '2 minutes',
            'icon': 'gratitude',
        },
    ],
}
