# Generated by Django 4.2 on 2026-07-01 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsightCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("declining", "Declining"),
                            ("stable", "Stable"),
                            ("insufficient_data", "Insufficient Data"),
                        ],
                        default="insufficient_data",
                        max_length=20,
                    ),
                ),
                ("correlation_strength", models.FloatField(blank=True, null=True)),
                ("insight_cards", models.JSONField(default=list)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_cache",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
