# Generated by Django 4.2 on 2026-07-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyroutine",
            name="icon",
            field=models.CharField(default="breath", max_length=50),
        ),
    ]
