# Generated by Django 4.2 on 2026-07-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IRELAND", "Ireland"),
                    ("UNITED_KINGDOM", "United Kingdom"),
                    ("UNITED_STATES", "United States"),
                    ("CANADA", "Canada"),
                    ("AUSTRALIA", "Australia"),
                ],
                default="IRELAND",
                max_length=20,
            ),
        ),
    ]
