# Generated by Django 4.2 on 2026-07-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="motherhood_stage",
            field=models.CharField(
                blank=True,
                choices=[("pregnant", "Pregnant"), ("postpartum", "Postpartum")],
                default="postpartum",
                max_length=20,
            ),
        ),
    ]
