# Generated by Django 4.2 on 2026-07-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notifications_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
