# Generated by Django 4.2 on 2026-07-16 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_notifications_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthcarecontact",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="healthcarecontact",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="healthcarecontact",
            name="relationship_type",
            field=models.CharField(
                choices=[
                    ("partner", "Partner"),
                    ("friend", "Best Friend"),
                    ("family", "Family"),
                    ("gp", "GP"),
                    ("midwife", "Midwife"),
                ],
                default="partner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="healthcarecontact",
            name="unique_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="healthcarecontact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="healthcare_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
