# Generated by Django 4.2 on 2026-07-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="baby_age_months",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="feeding_method",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="pregnancy_week",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="stage_reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="motherhood_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pregnant", "Pregnant"),
                    ("postpartum", "Postpartum"),
                    ("seasoned", "Seasoned mother"),
                    ("exploring", "Just exploring"),
                ],
                default="postpartum",
                max_length=20,
            ),
        ),
    ]
