# Generated by Django 4.2 on 2026-07-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_user_baby_age_months_user_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="epds_prompt_dismissed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
