# Generated by Django 4.2 on 2026-07-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearnTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("pregnant", "Pregnant"),
                            ("postpartum", "Postpartum"),
                            ("seasoned", "Seasoned mother"),
                            ("exploring", "Just exploring"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["stage", "order"],
            },
        ),
    ]
