# Generated by Django 4.2 on 2026-07-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkin",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="checkin",
            unique_together=set(),
        ),
    ]
