# Generated by Django 4.2 on 2026-07-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("love_note", "Love note"),
                    ("affirmation", "Affirmation"),
                    ("mood_alert", "Mood alert"),
                    ("epds_reminder", "EPDS reminder"),
                    ("routine", "Daily routine"),
                ],
                max_length=20,
            ),
        ),
    ]
